#!/bin/bash
am force-stop com.google.android.gms
am force-stop com.android.vending
pm clear com.google.android.play.games
pm clear com.google.android.webview
pm clear com.google.android.gsf.login
pm clear com.google.android.gsf
pm clear com.android.vending
pm clear com.google.android.gms
pm clear com.android.settings

pm clear com.android.vending
pm clear com.google.android.gms
pm clear com.google.android.gsf

su -c 'rm -rf /data/system/users/0/accounts.db'
su -c 'rm -rf /data/system_ce/0/accounts_ce.db'
su -c 'rm -rf /data/system_ce/0/accounts_ce.db-journal'
su -c 'rm -rf /data/system_de/0/accounts_de.db'
su -c 'rm -rf /data/system_de/0/accounts_de.db-journal'
su -c 'rm -rf /data/data/com.google.android.gms/databases/*'

am start -a android.settings.ADD_ACCOUNT_SETTINGS
input keyevent 4

